
import { Character, Weapon, Tome } from '../types';

export const CHARACTERS: Character[] = [
  { id: 'siroofie', name: 'Sir Oofie', image: 'assets/characters/SirOofie.png', defaultWeapon: 'Épée', defaultWeaponId: 'sword' },
  { id: 'fox', name: 'Fox', image: 'assets/characters/Fox.png', defaultWeapon: 'Bâton de feu', defaultWeaponId: 'firestaff' },
  { id: 'calcium', name: 'Calcium', image: 'assets/characters/Calcium_.png', defaultWeapon: 'Os', defaultWeaponId: 'bone' },
  { id: 'cl4nk', name: 'CL4NK', image: 'assets/characters/CL4NK_.png', defaultWeapon: 'Revolver', defaultWeaponId: 'revolver' },
  { id: 'athena', name: 'Athena', image: 'assets/characters/Athena.png', defaultWeapon: 'Égide', defaultWeaponId: 'aegis' },
  { id: 'ogre', name: 'Ogre', image: 'assets/characters/Ogre_.png', defaultWeapon: 'Hache', defaultWeaponId: 'axe' },
  { id: 'monke', name: 'Monke', image: 'assets/characters/Monke_.png', defaultWeapon: 'Banane', defaultWeaponId: 'banana' },
  { id: 'bush', name: 'Bush', image: 'assets/characters/Bush.png', defaultWeapon: 'Fusil de sniper', defaultWeaponId: 'sniperrifle' },
  { id: 'megachad', name: 'Megachad', image: 'assets/characters/Megachad_.png', defaultWeapon: 'Aura', defaultWeaponId: 'aura' },
  { id: 'robinette', name: 'Robinette', image: 'assets/characters/Robinette..png', defaultWeapon: 'Arc', defaultWeaponId: 'bow' },
  { id: 'tony', name: 'Tony McZoom', image: 'assets/characters/Tony_McZoom.png', defaultWeapon: 'Dague sans fil', defaultWeaponId: 'wirelessdagger' },
  { id: 'birdo', name: 'Birdo', image: 'assets/characters/Birdo.png', defaultWeapon: 'Tornade', defaultWeaponId: 'tornado' },
  { id: 'noelle', name: 'Noelle', image: 'assets/characters/Noelle.png', defaultWeapon: 'Marche givre', defaultWeaponId: 'frostwalker' },
  { id: 'amog', name: 'Amog', image: 'assets/characters/Amog.png', defaultWeapon: 'Fiole de poison', defaultWeaponId: 'poisonflask' },
  { id: 'spaceman', name: 'Spaceman', image: 'assets/characters/Spaceman_Logo.png', defaultWeapon: 'Trou noir', defaultWeaponId: 'blackhole' },
  { id: 'bandit', name: 'Bandit', image: 'assets/characters/Bandit.png', defaultWeapon: 'Dexécuteur', defaultWeaponId: 'dexecutioner' },
  { id: 'ninja', name: 'Ninja', image: 'assets/characters/Ninja_.png', defaultWeapon: 'Katana', defaultWeaponId: 'katana' },
  { id: 'vlad', name: 'Vlad', image: 'assets/characters/Vlad_Logo.png', defaultWeapon: 'Magie de sang', defaultWeaponId: 'bloodmagic' },
  { id: 'sirchadwell', name: 'Sir Chadwell', image: 'assets/characters/Sir_CHadwell.png', defaultWeapon: 'Épée corrompue', defaultWeaponId: 'corruptedsword' },
  { id: 'dicehead', name: 'Dicehead', image: 'assets/characters/Dicehead..png', defaultWeapon: 'Dé', defaultWeaponId: 'dice' }
];

export const WEAPONS: Weapon[] = [
  { id: 'aegis', name: 'Égide', image: 'assets/weapons/Aegis_Icon.jpg' },
  { id: 'aura', name: 'Aura', image: 'assets/weapons/Aura_Icon.jpg' },
  { id: 'axe', name: 'Hache', image: 'assets/weapons/Axe_Icon.jpg' },
  { id: 'banana', name: 'Banane', image: 'assets/weapons/Banana_Icon.jpg' },
  { id: 'blackhole', name: 'Trou noir', image: 'assets/weapons/BlackHole.jpg' },
  { id: 'bloodmagic', name: 'Magie de sang', image: 'assets/weapons/Blood_Magic.jpg' },
  { id: 'bone', name: 'Os', image: 'assets/weapons/Bone_Icon.jpg' },
  { id: 'bow', name: 'Arc', image: 'assets/weapons/Bow_Icon.jpg' },
  { id: 'chunker', name: 'Chunker', image: 'assets/weapons/Chunker_Icon.jpg' },
  { id: 'corruptedsword', name: 'Épée corrompue', image: 'assets/weapons/Corrupted_Sword.jpg' },
  { id: 'dexecutioner', name: 'Dexécuteur', image: 'assets/weapons/Dexecutioner.jpg' },
  { id: 'dice', name: 'Dé', image: 'assets/weapons/Dice.jpg' },
  { id: 'dragonsbreath', name: "Souffle du dragon", image: 'assets/weapons/Dragon\'s_Breath.jpg' },
  { id: 'firestaff', name: 'Bâton de feu', image: 'assets/weapons/Fire_Staff.jpg' },
  { id: 'firewalk', name: 'Marche de feu', image: 'assets/weapons/Firewalk.jpg' },
  { id: 'frostwalker', name: 'Marche givre', image: 'assets/weapons/Frost_walker.jpg' },
  { id: 'herosword', name: 'Épée héroïque', image: 'assets/weapons/Hero_Sword_Icon.jpg' },
  { id: 'katana', name: 'Katana', image: 'assets/weapons/Katana.jpg' },
  { id: 'lightningstaff', name: 'Bâton de foudre', image: 'assets/weapons/Lightning_Staff_Icon.jpg' },
  { id: 'mines', name: 'Mines', image: 'assets/weapons/Mines.jpg' },
  { id: 'poisonflask', name: 'Fiole de poison', image: 'assets/weapons/Poison_Flask_Icon.jpg' },
  { id: 'revolver', name: 'Revolver', image: 'assets/weapons/Revolver_Icon.jpg' },
  { id: 'shotgun', name: 'Fusil à pompe', image: 'assets/weapons/Shotgun.jpg' },
  { id: 'sluttyrocket', name: 'Roquette', image: 'assets/weapons/SluttyRocket.jpg' },
  { id: 'sniperrifle', name: 'Fusil de sniper', image: 'assets/weapons/Sniper_Rifle.jpg' },
  { id: 'spacenoodle', name: 'Nouille spatiale', image: 'assets/weapons/Space_Noodle.jpg' },
  { id: 'sword', name: 'Épée', image: 'assets/weapons/Sword_Icon.jpg' },
  { id: 'tornado', name: 'Tornade', image: 'assets/weapons/Tornado.jpg' },
  { id: 'wirelessdagger', name: 'Dague sans fil', image: 'assets/weapons/Wireless_Dagger.jpg' }
];

export const TOMES: Tome[] = [
  { id: 'agility', name: 'Tome d\'agilité', image: 'assets/tomes/Agility-Tome.png' },
  { id: 'armor', name: 'Tome d\'armure', image: 'assets/tomes/Armor-Tome.png' },
  { id: 'attraction', name: 'Tome d\'attraction', image: 'assets/tomes/Attraction-Tome.png' },
  { id: 'bloody', name: 'Tome sanglant', image: 'assets/tomes/Bloody-Tome.png' },
  { id: 'chaos', name: 'Tome de chaos', image: 'assets/tomes/Chaos_Tome.1.png' },
  { id: 'cooldown', name: 'Tome de récupération', image: 'assets/tomes/Cooldown-Tome.png' },
  { id: 'cursed', name: 'Tome maudit', image: 'assets/tomes/Cursed_Tome_Logo.png' },
  { id: 'damage', name: 'Tome de dégâts', image: 'assets/tomes/Damage-Tome.png' },
  { id: 'duration', name: 'Tome de durée', image: 'assets/tomes/Duration_Tome_Logo.png' },
  { id: 'evasion', name: 'Tome d\'évasion', image: 'assets/tomes/Evasion-Tome.png' },
  { id: 'gold', name: 'Tome d\'or', image: 'assets/tomes/Gold-Tome.png' },
  { id: 'hp', name: 'Tome de PV', image: 'assets/tomes/HP-Tome.png' },
  { id: 'knockback', name: 'Tome de recul', image: 'assets/tomes/Knockback-Tome.png' },
  { id: 'luck', name: 'Tome de chance', image: 'assets/tomes/Luck-Tome.png' },
  { id: 'precision', name: 'Tome de précision', image: 'assets/tomes/Precision-Tome.png' },
  { id: 'projectile', name: 'Tome de projectile', image: 'assets/tomes/Projectile-Tome.png' },
  { id: 'quantity', name: 'Tome de quantité', image: 'assets/tomes/Quantity-Tome.png' },
  { id: 'regen', name: 'Tome de régénération', image: 'assets/tomes/Regen-Tome.png' },
  { id: 'shield', name: 'Tome de bouclier', image: 'assets/tomes/Shield-Tome.png' },
  { id: 'silve', name: 'Tome d\'argent', image: 'assets/tomes/Silve-Tome.png' },
  { id: 'size', name: 'Tome de taille', image: 'assets/tomes/Size-Tome.png' },
  { id: 'thorns', name: 'Tome d\'épines', image: 'assets/tomes/Thorns_Tome_Logo.png' },
  { id: 'xp', name: 'Tome d\'XP', image: 'assets/tomes/XP-Tome.png' }
];

