"use strict";
/**
 * Données du jeu - Personnages, Armes et Tomes
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TOMES = exports.WEAPONS = exports.CHARACTERS = void 0;
exports.CHARACTERS = [
    { id: 'siroofie', name: 'Sir Oofie', image: 'assets/characters/SirOofie.png', defaultWeapon: 'Sword', defaultWeaponId: 'sword' },
    { id: 'fox', name: 'Fox', image: 'assets/characters/Fox.png', defaultWeapon: 'Fire Staff', defaultWeaponId: 'firestaff' },
    { id: 'calcium', name: 'Calcium', image: 'assets/characters/Calcium_.png', defaultWeapon: 'Bone', defaultWeaponId: 'bone' },
    { id: 'cl4nk', name: 'CL4NK', image: 'assets/characters/CL4NK_.png', defaultWeapon: 'Revolver', defaultWeaponId: 'revolver' },
    { id: 'athena', name: 'Athena', image: 'assets/characters/Athena.png', defaultWeapon: 'Aegis', defaultWeaponId: 'aegis' },
    { id: 'ogre', name: 'Ogre', image: 'assets/characters/Ogre_.png', defaultWeapon: 'Axe', defaultWeaponId: 'axe' },
    { id: 'monke', name: 'Monke', image: 'assets/characters/Monke_.png', defaultWeapon: 'Banana', defaultWeaponId: 'banana' },
    { id: 'bush', name: 'Bush', image: 'assets/characters/Bush.png', defaultWeapon: 'Sniper Rifle', defaultWeaponId: 'sniperrifle' },
    { id: 'megachad', name: 'Megachad', image: 'assets/characters/Megachad_.png', defaultWeapon: 'Aura', defaultWeaponId: 'aura' },
    { id: 'robinette', name: 'Robinette', image: 'assets/characters/Robinette..png', defaultWeapon: 'Bow', defaultWeaponId: 'bow' },
    { id: 'tony', name: 'Tony McZoom', image: 'assets/characters/Tony_McZoom.png', defaultWeapon: 'Wireless Dagger', defaultWeaponId: 'wirelessdagger' },
    { id: 'birdo', name: 'Birdo', image: 'assets/characters/Birdo.png', defaultWeapon: 'Tornado', defaultWeaponId: 'tornado' },
    { id: 'noelle', name: 'Noelle', image: 'assets/characters/Noelle.png', defaultWeapon: 'Frost Walker', defaultWeaponId: 'frostwalker' },
    { id: 'amog', name: 'Amog', image: 'assets/characters/Amog.png', defaultWeapon: 'Poison Flask', defaultWeaponId: 'poisonflask' },
    { id: 'spaceman', name: 'Spaceman', image: 'assets/characters/Spaceman_Logo.png', defaultWeapon: 'Black Hole', defaultWeaponId: 'blackhole' },
    { id: 'bandit', name: 'Bandit', image: 'assets/characters/Bandit.png', defaultWeapon: 'Dexecutioner', defaultWeaponId: 'dexecutioner' },
    { id: 'ninja', name: 'Ninja', image: 'assets/characters/Ninja_.png', defaultWeapon: 'Katana', defaultWeaponId: 'katana' },
    { id: 'vlad', name: 'Vlad', image: 'assets/characters/Vlad_Logo.png', defaultWeapon: 'Blood Magic', defaultWeaponId: 'bloodmagic' },
    { id: 'sirchadwell', name: 'Sir Chadwell', image: 'assets/characters/Sir_CHadwell.png', defaultWeapon: 'Corrupted Sword', defaultWeaponId: 'corruptedsword' },
    { id: 'dicehead', name: 'Dicehead', image: 'assets/characters/Dicehead..png', defaultWeapon: 'Dice', defaultWeaponId: 'dice' }
];
exports.WEAPONS = [
    { id: 'aegis', name: 'Aegis', image: 'assets/weapons/Aegis_Icon.jpg' },
    { id: 'aura', name: 'Aura', image: 'assets/weapons/Aura_Icon.jpg' },
    { id: 'axe', name: 'Axe', image: 'assets/weapons/Axe_Icon.jpg' },
    { id: 'banana', name: 'Banana', image: 'assets/weapons/Banana_Icon.jpg' },
    { id: 'blackhole', name: 'Black Hole', image: 'assets/weapons/BlackHole.jpg' },
    { id: 'bloodmagic', name: 'Blood Magic', image: 'assets/weapons/Blood_Magic.jpg' },
    { id: 'bone', name: 'Bone', image: 'assets/weapons/Bone_Icon.jpg' },
    { id: 'bow', name: 'Bow', image: 'assets/weapons/Bow_Icon.jpg' },
    { id: 'chunker', name: 'Chunker', image: 'assets/weapons/Chunker_Icon.jpg' },
    { id: 'corruptedsword', name: 'Corrupted Sword', image: 'assets/weapons/Corrupted_Sword.jpg' },
    { id: 'dexecutioner', name: 'Dexecutioner', image: 'assets/weapons/Dexecutioner.jpg' },
    { id: 'dice', name: 'Dice', image: 'assets/weapons/Dice.jpg' },
    { id: 'dragonsbreath', name: "Dragon's Breath", image: 'assets/weapons/Dragon\'s_Breath.jpg' },
    { id: 'firestaff', name: 'Fire Staff', image: 'assets/weapons/Fire_Staff.jpg' },
    { id: 'firewalk', name: 'Firewalk', image: 'assets/weapons/Firewalk.jpg' },
    { id: 'frostwalker', name: 'Frost Walker', image: 'assets/weapons/Frost_walker.jpg' },
    { id: 'herosword', name: 'Hero Sword', image: 'assets/weapons/Hero_Sword_Icon.jpg' },
    { id: 'katana', name: 'Katana', image: 'assets/weapons/Katana.jpg' },
    { id: 'lightningstaff', name: 'Lightning Staff', image: 'assets/weapons/Lightning_Staff_Icon.jpg' },
    { id: 'mines', name: 'Mines', image: 'assets/weapons/Mines.jpg' },
    { id: 'poisonflask', name: 'Poison Flask', image: 'assets/weapons/Poison_Flask_Icon.jpg' },
    { id: 'revolver', name: 'Revolver', image: 'assets/weapons/Revolver_Icon.jpg' },
    { id: 'shotgun', name: 'Shotgun', image: 'assets/weapons/Shotgun.jpg' },
    { id: 'sluttyrocket', name: 'Slutty Rocket', image: 'assets/weapons/SluttyRocket.jpg' },
    { id: 'sniperrifle', name: 'Sniper Rifle', image: 'assets/weapons/Sniper_Rifle.jpg' },
    { id: 'spacenoodle', name: 'Space Noodle', image: 'assets/weapons/Space_Noodle.jpg' },
    { id: 'sword', name: 'Sword', image: 'assets/weapons/Sword_Icon.jpg' },
    { id: 'tornado', name: 'Tornado', image: 'assets/weapons/Tornado.jpg' },
    { id: 'wirelessdagger', name: 'Wireless Dagger', image: 'assets/weapons/Wireless_Dagger.jpg' }
];
exports.TOMES = [
    { id: 'agility', name: 'Agility Tome', image: 'assets/tomes/Agility-Tome.png' },
    { id: 'armor', name: 'Armor Tome', image: 'assets/tomes/Armor-Tome.png' },
    { id: 'attraction', name: 'Attraction Tome', image: 'assets/tomes/Attraction-Tome.png' },
    { id: 'bloody', name: 'Bloody Tome', image: 'assets/tomes/Bloody-Tome.png' },
    { id: 'chaos', name: 'Chaos Tome', image: 'assets/tomes/Chaos_Tome.1.png' },
    { id: 'cooldown', name: 'Cooldown Tome', image: 'assets/tomes/Cooldown-Tome.png' },
    { id: 'cursed', name: 'Cursed Tome', image: 'assets/tomes/Cursed_Tome_Logo.png' },
    { id: 'damage', name: 'Damage Tome', image: 'assets/tomes/Damage-Tome.png' },
    { id: 'duration', name: 'Duration Tome', image: 'assets/tomes/Duration_Tome_Logo.png' },
    { id: 'evasion', name: 'Evasion Tome', image: 'assets/tomes/Evasion-Tome.png' },
    { id: 'gold', name: 'Gold Tome', image: 'assets/tomes/Gold-Tome.png' },
    { id: 'hp', name: 'HP Tome', image: 'assets/tomes/HP-Tome.png' },
    { id: 'knockback', name: 'Knockback Tome', image: 'assets/tomes/Knockback-Tome.png' },
    { id: 'luck', name: 'Luck Tome', image: 'assets/tomes/Luck-Tome.png' },
    { id: 'precision', name: 'Precision Tome', image: 'assets/tomes/Precision-Tome.png' },
    { id: 'projectile', name: 'Projectile Tome', image: 'assets/tomes/Projectile-Tome.png' },
    { id: 'quantity', name: 'Quantity Tome', image: 'assets/tomes/Quantity-Tome.png' },
    { id: 'regen', name: 'Regen Tome', image: 'assets/tomes/Regen-Tome.png' },
    { id: 'shield', name: 'Shield Tome', image: 'assets/tomes/Shield-Tome.png' },
    { id: 'silve', name: 'Silve Tome', image: 'assets/tomes/Silve-Tome.png' },
    { id: 'size', name: 'Size Tome', image: 'assets/tomes/Size-Tome.png' },
    { id: 'thorns', name: 'Thorns Tome', image: 'assets/tomes/Thorns_Tome_Logo.png' },
    { id: 'xp', name: 'XP Tome', image: 'assets/tomes/XP-Tome.png' }
];
